name: Release workflow

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add the package to the release
        run: gh release upload ${{github.event.release.tag_name}} src/index.html
        env:
          GH_TOKEN: ${{ github.token }}
